spring:
  datasource:
    url: jdbc:h2:mem:contentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: brian981103

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


jwt:
  access:
    secret: "9uMDsQmC38C8ImGMeiRC2CDHhP5eUoq3NThQIfiy6zU="
    expiration: 1h